name: Deploy to Azure Static Web Apps

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  issues: write

env:
  APP_LOCATION: apps/web
  API_LOCATION: apps/api
  OUTPUT_LOCATION: dist

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20 + Corepack
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable

      # Build front (Vite)
      - name: Build web
        working-directory: ${{ env.APP_LOCATION }}
        run: |
          pnpm install --frozen-lockfile=false
          pnpm build

      # Build API (Functions v4 ESM)
      - name: Build api
        working-directory: ${{ env.API_LOCATION }}
        run: |
          pnpm install --frozen-lockfile=false
          pnpm build

      # Déploiement SWA (on réutilise le builder SWA mais on lui donne nos sorties)
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: ${{ env.APP_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          app_build_command: "echo Build already done"
          api_location: ${{ env.API_LOCATION }}
          api_build_command: "echo Build already done"
