name: Deploy to Azure Static Web Apps

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.16.1
          run_install: false
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install workspace deps
        run: pnpm install --frozen-lockfile=false

      - name: Build web
        run: pnpm -C apps/web build

      - name: Build api
        run: pnpm -C apps/api build

      # Node modules prod pour Functions (runtime)
      - name: API runtime deps only
        run: pnpm -C apps/api install --prod --no-optional

      - name: Deploy to Azure Static Web Apps (upload prebuilt)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: apps/web
          app_artifact_location: apps/web/dist
          skip_app_build: true
          api_location: apps/api
          skip_api_build: true
