# .github/workflows/swa.yml
name: Deploy to Azure Static Web Apps

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20 + Corepack
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: corepack enable

      - name: Install workspace deps
        run: pnpm install --frozen-lockfile=false

      - name: Build web
        run: pnpm -C apps/web build

      - name: Build api
        run: pnpm -C apps/api build

      - name: API runtime deps only
        run: pnpm -C apps/api install --prod --no-optional

      - name: Deploy to Azure Static Web Apps (upload prebuilt)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          # On envoie directement les artefacts compilés :
          app_location: apps/web
          app_artifact_location: apps/web/dist
          skip_app_build: true
          api_location: apps/api
          skip_api_build: true
