# .github/workflows/swa.yml
name: Deploy to Azure Static Web Apps

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.16.1
          run_install: false

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install workspace deps
        run: pnpm install --frozen-lockfile=false

      - name: Build web (Vite)
        run: pnpm -C apps/web build

      - name: Build api (Functions ESM)
        run: pnpm -C apps/api build

      # Dépendances runtime (prod) pour l’API côté Functions
      - name: API runtime deps only
        run: pnpm -C apps/api install --prod --no-optional

      - name: Inspect API zip content (pre-upload)
        run: |
          echo "--- api package.json ---"
          cat apps/api/package.json
          echo "--- api host.json ---"
          cat apps/api/host.json
          echo "--- dist functions ---"
          ls -la apps/api/dist/src
          ls -la apps/api/dist/src/functions

      # (debug) montrer exactement ce qu’on va déployer
      - name: Inspect artifact that will be uploaded
        run: |
          echo "--- index.html ---"
          sed -n '1,120p' apps/web/dist/index.html
          echo "--- assets ---"
          ls -la apps/web/dist/assets
          echo "--- staticwebapp.config.json ---"
          cat apps/web/dist/staticwebapp.config.json

      - name: Deploy to Azure Static Web Apps (upload prebuilt)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          # ⚠️ On envoie le dossier DIST lui-même (et rien d’autre) :
          app_location: apps/web/dist
          app_artifact_location: .
          skip_app_build: true
          # ⚠️ On envoie le dossier de l’API déjà compilé :
          api_location: apps/api
          skip_api_build: true
